version: "3.8"

services:
    backend:
        build:
            context: .
            dockerfile: Dockerfile
        command: uvicorn main:app --reload --workers 1 --host 0.0.0.0 --port 8000
        volumes:
            - ./JeffQL:/usr/src/app
        ports:
            - 8000:8000
        environment:
            - ENVIRONMENT=dev
            - TESTING=0